import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { WindowSizeProvider } from "@/contexts/WindowWidthContext";
import { IsOpenContactProvider } from "@/contexts/IsOpenContact";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { IsOpenSidebarSecondProvider } from "@/contexts/IsOpenSidebarSecond";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang="en">
      <body className={`${inter.className} w-fit h-fit relative`}>
        <WindowSizeProvider>
          <IsOpenContactProvider>
            <IsOpenSidebarSecondProvider>
              <ThemeProvider>
                  {children}
                </ThemeProvider>
            </IsOpenSidebarSecondProvider>
          </IsOpenContactProvider>
        </WindowSizeProvider>
      </body>
    </html>
  );
}
